

export default [
  {
    id: 1,
    img: "/image/japan...jpeg",
    country: "Japan",
    link: "https://maps.app.goo.gl/sAeoiW4Ye9bz8TtA9",
    cityName: "Tokyo",
    population: "124,631,000",
    bio: "Japan has over 125 million inhabitants and is the 11th most populous country in the world, as well as one of the most densely populated. About three-fourths of the country's terrain is mountainous, concentrating its highly urbanized population on narrow coastal plains.",
  },
  {
    id: 2,
    img: "/image/usa.jpeg",
    country: "United State",
    link: "https://maps.app.goo.gl/SYqnqMNWMbraYea16",
    cityName: "Washington DC.",
    population: "334,914,895",
    bio: "The U.S. is a country of 50 states covering a vast swath of North America, with Alaska in the northwest and Hawaii extending the nation’s presence into the Pacific Ocean. Major Atlantic Coast cities are New York, a global finance and culture center, and capital Washington, DC. ",
  },
  {
    id: 3,
    img: "/image/dubai.jpeg",
    country: "Uae",
    link: "https://maps.app.goo.gl/PUNqGnwfKucFX5ZG9",
    cityName: "Dubai",
    population: "9,282,410",
    bio: "The United Arab Emirates, or simply the Emirates, is a country in West Asia, in the Middle East. It is located at the eastern end of the Arabian Peninsula and shares borders with Oman and Saudi Arabia, while also having maritime borders in the Persian Gulf with Qatar and Iran.",
  },
  {
    id: 4,
    img: "/image/london1.jpeg",
    country: "United Kingdom",
    link: "https://maps.app.goo.gl/pqhR4xm8teLYwJYt6",
    cityName: "London",
    population: "66,971,395",
    bio: "The United Kingdom, made up of England, Scotland, Wales and Northern Ireland, is an island nation in northwestern Europe. England – birthplace of Shakespeare and The Beatles – is home to the capital, London, a globally influential centre of finance and culture.",
  },
  {
    id: 5,
    img: "/image/singapore.jpeg",
    country: "Republic of Singapore",
    link: "https://maps.app.goo.gl/fXdx9YpnsbtEsrtX9",
    cityName: "Singapore",
    population: "5,917,600",
    bio: "Singapore, officially the Republic of Singapore, is an island country and city-state in maritime Southeast Asia. After early years of turbulence and despite lacking natural resources and a hinterland, the nation rapidly developed to become one of the Four Asian Tigers. ",
  },
  {
    id: 6,
    img: "/image/nigeria.jpeg",
    country: "Nigeria",
    link: "https://maps.app.goo.gl/JC7DgGfsK5Px7TzK9",
    cityName: "Abuja",
    population: "230,842,743",
    bio: "Nigeria, an African country on the Gulf of Guinea, has many natural landmarks and wildlife reserves. Protected areas such as Cross River National Park and Yankari National Park have waterfalls, dense rainforest, savanna and rare primate habitats.",
  },
  {
    id: 7,
    img: "/image/turkey.jpeg",
    country: "Republic of Turkey",
    link: "https://maps.app.goo.gl/opodymHkjY83pN576",
    cityName: "Ankara",
    population: "85,279,553",
    bio: "Turkey, officially the Republic of Türkiye, is a country in Southeast Europe and West Asia. It is mainly on the Anatolian Peninsula in West Asia, with a small portion called East Thrace on the Balkan Peninsula in Southeast Europe. ",
  },
  {
    id: 8,
    img: "/image/canada.webp",
    country: "Canada",
    link: "https://maps.app.goo.gl/mbMg8GmYTV49drpT9",
    cityName: "Ottawa",
    population: "40,528,396",
    bio: "Canada is a country in North America. Its ten provinces and three territories extend from the Atlantic Ocean to the Pacific Ocean and northward into the Arctic Ocean, making it the world's second-largest country by total area, with the world's longest coastline.",
  },
  {
    id: 9,
    img: "/image/germany.jpeg",
    country: "Germany",
    link: "https://maps.app.goo.gl/dv6TzWu2vC6p5QbWA",
    cityName: "Berlin",
    population: "84,607,016",
    bio: "Germany is a Western European country with a landscape of forests, rivers, mountain ranges and North Sea beaches. It has over 2 millennia of history. Berlin, its capital, is home to art and nightlife scenes, the Brandenburg Gate and many sites relating to WWII. ",
  },
  {
    id: 9,
    img: "/image/qatar...jpeg",
    country: "Qatar",
    link: "https://maps.app.goo.gl/6J7FHVf1HrNrzR2Z6",
    cityName: "Doha",
    population: "2,795,484",
    bio: "Doha is the capital city and main financial hub of Qatar. Located on the Persian Gulf coast in the east of the country, north of Al Wakrah and south of Al Khor, it is home to most of the country's population. Doha is the capital city and main financial hub of Qatar.",
  }
];
